[tools]
node = "lts"
pnpm = "latest"

[tasks.build]
description = "Build the monorepo"
run = "pnpm -r run build"

[tasks.test]
description = "Run vitest tests"
run = "pnpm vitest run"

[tasks.lint]
description = "Run ESLint"
run = "pnpm eslint --fix ."

[tasks.format]
description = "Format with Prettier"
run = "pnpm prettier --write ."

[tasks.jscpd]
description = "Run JSCPD to check for duplicated code"
run = "pnpm jscpd ."
